version: "3.7"
services:

  mysql8027:
    # container name
    container_name: mysql_8_0_31
    # image version
    image: mysql:8.0.31
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Taipei
      LANG=C: UTF-8
    volumes:
      # init database
      - ./init:/docker-entrypoint-initdb.d
    command:
      - --lower_case_table_names=1
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+08:00
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    security_opt:
      - seccomp:unconfined
